#!/usr/bin/env python

#------------------------------------------------------------------------------

import sys
import getopt

#------------------------------------------------------------------------------

class App :
	name = "xconst"
	version = "0.0.1"
	author = ["Yasuhiro Kanda"]


def usage () :
	print App . name
	print App . version ""
	print App . author
	print """
USAGE
		
OPTIONS
 -h, --h
 -v, --version
 -i, --input
 -o, --output
	"""
	


#------------------------------------------------------------------------------

def main () :

	# 引数パース処理
	try :
		optlist, args = getopt . getopt (sys . argv[1:], "hvi:o:", longopts=["help", "version", "input_file=, output_file="])

	except getopt . GetoptError :
		usage ()
		sys . exit (1)
	
	
	# 入力ファイル、出力ファイルを受け取る変数
	in_file = ""
	ex_file = ""

	for opt, arg in optlist :
		if opt in ("-h", "--help") :
			usage ()
			sys . exit (0)

		if opt in ("-v", "--version") :
			print "xconst, version " + App . version
			sys . exit (0)


		# 入力ファイル名を受け取る
		if opt in ("-i", "--input_file") :
			in_file = arg
		
		# 出力ファイル名を受け取る
		if opt in ("-o", "--output_file") :
			ex_file = arg


		# 出力ファイル名が設定されなかった場合、入力ファイル名のベースネームを用いる
		if "" == ex_file :


#------------------------------------------------------------------------------

if __name__ == '__main__' :
	main ()
